import type { NextPage } from "next";
import Head from "next/head";
import { About, Blogs, Contact, Footer, Hero, Menu, NavBar, Products, Review } from "../component/HomePage";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        ></link>
      </Head>

      <main>
        <NavBar />
        <Hero />
        <About />
        <Products />
        <Menu />
        <Review />
        <Contact />
        <Blogs />
        <Footer />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
