import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { About, Blogs, Contact, Footer, Hero, Menu, NavBar, Products, Review } from "../component/HomePage";
import { getAllBlogs } from "../helpers/blogs-utils";
import { Blog } from "../model/Blog";
import { MenuItem } from "../model/Menu";
import { getMenuItems } from "../services/Menu";

interface HompageProps {
  menuItems: MenuItem[];
  blogs: Blog[];
}

const Home: NextPage<HompageProps> = (props) => {
  const { menuItems, blogs } = props;
  return (
    <div>
      <Head>
        <title>Next Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        ></link>
      </Head>

      <main>
        <NavBar />
        <Hero />
        <About />
        <Products />
        <Menu menuItems={menuItems} />
        <Review />
        <Contact />
        <Blogs blogs={blogs} />
        <Footer />
      </main>

      <footer></footer>
    </div>
  );
};


export const getStaticProps = async () => {
  const menuItems = await getMenuItems();
  const blogs = getAllBlogs();

  return {
    props: {
      menuItems: JSON.parse(JSON.stringify(menuItems)),
      blogs: blogs
    }
  };
}

export default Home;
